// DASHBOARD
export const LIST_DASHBOARD = 'LIST_DASHBOARD';
export const LIST_DASHBOARD_SUCCESS = 'LIST_DASHBOARD_SUCCESS';
export const LIST_DASHBOARD_ERROR = 'LIST_DASHBOARD_ERROR';

// EMPLOYEE
export const LIST_EMPLOYEE = 'LIST_EMPLOYEE';
export const LIST_EMPLOYEE_SUCCESS = 'LIST_EMPLOYEE_SUCCESS';
export const LIST_EMPLOYEE_ERROR = 'LIST_EMPLOYEE_ERROR';

// STORE
export const LIST_STORE = 'LIST_STORE';
export const LIST_STORE_SUCCESS = 'LIST_STORE_SUCCESS';
export const LIST_STORE_ERROR = 'LIST_STORE_ERROR';